package hr.fer.zemris.java.hw06.shell;


import java.io.File;
import java.util.List;
import java.util.regex.Matcher;

/**
 * Represents one file that has been filtered.
 * COntains number of groups that were generated in filtering and list of those groups.
 * @author Martina
 *
 */
public class FilterResult {

	File file;
	List<String> groups;
	int numberOfGroups;
	
	/**
	 * Constructor method for creating one {@link FilterResult} object.
	 * 
	 * @param file	file to be saved
	 * @param groups	strings generated by matcher when filtering
	 * @param numberOfGroups	numbee of groups for this file
	 */
	public FilterResult(File file, List<String> groups, int numberOfGroups) {
		super();
		this.file = file;
		this.groups = groups;
		this.numberOfGroups = numberOfGroups;
	}


	@Override
	public String toString() {
		return file.getName();
		
	}
	
	/**
	 * Returns number of groups for this {@link FilterResult} file.
	 * @return
	 */
	public int numberOfGroups() {
		return numberOfGroups;
		
	}
	
	/**
	 * Returns all the generated groups by {@link Matcher} object for this file.
	 * 
	 * @param index index of group to return
	 * @return	group at specified index
	 */
	public String group(int index) {
		return groups.get(index);
	}
	
}
