package hr.fer.zemris.java.hw17.jvdraw.visitors;

import hr.fer.zemris.java.hw17.jvdraw.GeometricalObjectVisitor;
import hr.fer.zemris.java.hw17.jvdraw.objects.Circle;
import hr.fer.zemris.java.hw17.jvdraw.objects.FilledCircle;
import hr.fer.zemris.java.hw17.jvdraw.objects.Line;

/**
 * Class used when saving a text representation of some painted picture with objects.
 * 
 * @author Martina
 *
 */
public class GeometricObjectSaveVisitor implements GeometricalObjectVisitor {

	/**
	 * Generated value.
	 */
	String value;
	
	public GeometricObjectSaveVisitor(String value) {
		this.value = value;
	}
	@Override
	public void visit(Line line) {
		value += "LINE " + String.format("%d %d %d %d %d %d %d", line.getStart().x, line.getStart().y, line.getEnd().x, line.getEnd().y, 
						  line.getColor().getRed(), line.getColor().getGreen(), line.getColor().getBlue()) + "\n";

	}

	@Override
	public void visit(Circle circle) {
		value += "CIRCLE " + String.format("%d %d %d %d %d %d", circle.getCenter().x, circle.getCenter().y, circle.getRadius(),
				  circle.getColor().getRed(), circle.getColor().getGreen(), circle.getColor().getBlue()) + "\n";

	}

	@Override
	public void visit(FilledCircle filledCircle) {
		value += "FCIRCLE " + String.format("%d %d %d %d %d %d %d %d %d", filledCircle.getCenter().x, filledCircle.getCenter().y, filledCircle.getRadius(),
				filledCircle.getLineColor().getRed(), filledCircle.getLineColor().getGreen(), filledCircle.getLineColor().getBlue(),
				filledCircle.getFillColor().getRed(), filledCircle.getFillColor().getGreen(), filledCircle.getFillColor().getBlue()) + "\n";

	}

	/**
	 * Returns String value generated by visiting all objects.
	 * @return
	 */
	public String getValue() {
		return value.substring(0, value.length()-1);
	}
}
