package hr.fer.zemris.java.hw05.db;

import java.util.List;

/**
 * Represents an object to be generated by lexer from some query string.
 * Each instance of this class has a list of conditional objects and a type.
 * 
 * @author Martina
 *
 */
public class Query {
	
	//type of query, can be regular or other
	QueryType type;
	
	//conditional expressions generated from a query string
	private List<ConditionalExpression> conditionalExpressions;
	
	
	/**
	 * Constructor class for creating one {@link Query} object.
	 * 
	 * @param type	{@link QueryType} of new object
	 * @param conditionalExpressions {@link List} of {@link ConditionalExpression} objects
	 */
	public Query(QueryType type, List<ConditionalExpression> conditionalExpressions) {
		super();
		this.type = type;
		this.conditionalExpressions = conditionalExpressions;
	}

	/**
	 * Returns type of this query.
	 * @return type of this query
	 */
	public QueryType getType() {
		return type;
	}

	/**
	 * Returns a list of {@link ConditionalExpression} objects for this query.
	 * 
	 * @return	list of all {@link ConditionalExpression} objects.
	 */
	public List<ConditionalExpression> getConditionalExpressions() {
		return conditionalExpressions;
	}
	
	
}
