package hr.fer.zemris.java.hw08.massrename;


/**
 * Represents one token to be generated by lexer.
 * 
 * @author Martina
 *
 */
public class Token {

	TokenType type;
	String content;
	
	/**
	 * Constructor for creating one {@link Token}.
	 * 
	 * @param type		type of a new token
	 * @param content	string to be stored in this token
	 */
	public Token(TokenType type, String content) {
		super();
		this.type = type;
		this.content = content;
	}

	/**
	 * Returns this token's type.
	 * 
	 * @return token type
	 */
	public TokenType getType() {
		return type;
	}

	/**
	 * Returns string content of this token.
	 * 
	 * @return	retruns content of this token
	 */
	public String getContent() {
		return content;
	}
	
	
}
